<x-guest-layout>
    <!-- Session Status -->
    <x-auth-session-status class="mb-4" :status="session('status')" />

    <div x-data="neuralAuth()">
        <!-- Form UI -->
        <form id="cyberLoginForm" method="POST" action="{{ route('login') }}" x-ref="loginForm" @submit.prevent="initiateLink">
            @csrf
            
            <div class="mb-4 text-center">
                <span class="text-xs text-[var(--electric-blue)] font-mono tracking-widest break-all opacity-80">CONNECTING TO SECURE MAINFRAME...</span>
            </div>
            
            <div class="mb-6 flex justify-center gap-6 text-sm font-mono tracking-widest uppercase">
                <button type="button" @click="loginMode = 'standard'" :class="loginMode == 'standard' ? 'text-[var(--electric-blue)] border-b border-[var(--electric-blue)] font-bold shadow-[0_4px_10px_-2px_var(--electric-blue)]' : 'text-gray-500 hover:text-[var(--electric-blue)] transition-colors'" class="pb-1 transition-all">Neural ID</button>
                <button type="button" @click="loginMode = 'faceid'" :class="loginMode == 'faceid' ? 'text-[var(--electric-blue)] border-b border-[var(--electric-blue)] font-bold shadow-[0_4px_10px_-2px_var(--electric-blue)]' : 'text-gray-500 hover:text-[var(--electric-blue)] transition-colors'" class="pb-1 transition-all">Biometric</button>
            </div>

            <div x-show="loginMode == 'standard'" x-transition>
                <!-- Email Address -->
                <div>
                    <label for="email" class="block font-mono text-xs text-[var(--electric-blue)] uppercase tracking-widest opacity-80">Neural ID (Email)</label>
                    <input id="email" class="block mt-1 w-full flex-1 bg-transparent border-b border-gray-700 outline-none pb-1 text-[var(--electric-blue)] focus:border-[var(--electric-blue)] transition-colors font-mono" type="email" name="email" value="{{ old('email') }}" autofocus autocomplete="username" :required="loginMode == 'standard'" />
                    <x-input-error :messages="$errors->get('email')" class="mt-2 text-red-500 font-mono text-xs" />
                </div>

                <!-- Password -->
                <div class="mt-6">
                    <label for="password" class="block font-mono text-xs text-[var(--electric-blue)] uppercase tracking-widest opacity-80">Access Code (Password)</label>
                    <input id="password" class="block mt-1 w-full bg-transparent border-b border-gray-700 outline-none pb-1 text-[var(--electric-blue)] focus:border-[var(--electric-blue)] transition-colors font-mono" type="password" name="password" autocomplete="current-password" :required="loginMode == 'standard'" />
                    <x-input-error :messages="$errors->get('password')" class="mt-2 text-red-500 font-mono text-xs" />
                </div>
            </div>
            
            <div x-show="loginMode == 'faceid'" style="display: none;" x-transition>
                 <div>
                    <label for="face_id_token" class="block font-mono text-xs text-[var(--electric-blue)] uppercase tracking-widest opacity-80">Biometric Security Hash</label>
                    <input id="face_id_token" class="block mt-1 w-full bg-transparent border-b border-gray-700 outline-none pb-1 text-[var(--electric-blue)] focus:border-[var(--electric-blue)] transition-colors font-mono" type="password" name="face_id_token" autocomplete="off" :required="loginMode == 'faceid'" />
                    <p class="text-sm text-gray-500 mt-2 uppercase tracking-wide">Enter the Face ID Hash generated by admin. The system will mock facial resonance vector matching.</p>
                    <x-input-error :messages="$errors->get('face_id_token')" class="mt-2 text-red-500 font-mono text-xs" />
                 </div>
            </div>

            <div class="flex items-center justify-between mt-8">
                <button type="submit" class="w-full bg-transparent border border-[var(--cyber-yellow)] text-[var(--cyber-yellow)] py-3 uppercase tracking-widest font-bold font-orbitron hover:bg-[var(--cyber-yellow)] hover:text-[var(--bg-color)] transition-all duration-300 relative group shadow-[0_0_15px_rgba(252,238,10,0.2)]">
                    <span class="group-hover:cyber-glitch transition-all">INITIATE CONNECTION</span>
                </button>
            </div>
        </form>

        <!-- Face ID Liveness Detection Overlay -->
        <div x-show="scanning" style="display: none;" class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-95 backdrop-blur-md">
            <div class="text-center relative cyber-panel p-8 shadow-[0_0_30px_rgba(0,240,255,0.2)]">
                <div class="relative w-48 h-48 mx-auto mb-6 border border-gray-700 bg-black rounded-full flex items-center justify-center overflow-hidden shadow-[0_0_20px_rgba(0,240,255,0.1)]">
                    <!-- Camera Video -->
                    <video id="faceIdVideo" autoplay muted playsinline class="absolute inset-0 object-cover w-full h-full opacity-70 transform scale-x-[-1]"></video>

                    <!-- Scanner beam -->
                    <div class="absolute inset-0 flex items-center justify-center mix-blend-screen text-[var(--electric-blue)] opacity-40">
                        <svg class="w-full h-full p-4" viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="1"><path d="M20 30 V20 H30 M70 20 H80 V30 M80 70 V80 H70 M30 80 H20 V70" stroke-linecap="square"/></svg>
                    </div>
                    <div class="absolute inset-x-0 h-1 bg-[var(--electric-blue)] shadow-[0_0_10px_var(--electric-blue)] z-20 pointer-events-none" style="top: 0; animation: scan 2s linear infinite"></div>
                    
                    <style>
                        @keyframes scan { 100% { top: 100%; } }
                    </style>
                </div>
                <h2 class="text-lg font-orbitron font-bold text-[var(--electric-blue)] mb-2 uppercase tracking-widest">Biometric Validation</h2>
                <p class="text-[var(--electric-blue)] font-mono text-xs uppercase tracking-widest glitch-anim" x-text="scanMessage"></p>
                <div class="w-full h-1 bg-gray-900 mx-auto mt-4">
                    <div class="h-full bg-[var(--electric-blue)] transition-all duration-500" :style="'width: ' + progress + '%'"></div>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('alpine:init', () => {
            Alpine.data('neuralAuth', () => ({
                loginMode: '{{ (old('face_id_token') || $errors->has('face_id_token')) ? 'faceid' : 'standard' }}',
                scanning: false,
                progress: 0,
                scanMessage: 'INITIALIZING CAMERA...',
                initiateLink() {
                    this.scanning = true;
                    this.progress = 10;
                    this.scanMessage = 'ACCESSING BIOMETRICS...';
                    
                    // Access Web Camera
                    const video = document.getElementById('faceIdVideo');
                    if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                        navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" } })
                            .then(function(stream) {
                                video.srcObject = stream;
                            })
                            .catch(function(error) {
                                console.log("Camera access denied", error);
                            });
                    }
                    
                    setTimeout(() => {
                        this.progress = 50;
                        this.scanMessage = 'ANALYZING NEURAL PATTERNS...';
                    }, 1500);

                    setTimeout(() => {
                        this.progress = 90;
                        this.scanMessage = 'VERIFYING IDENTITY...';
                    }, 3000);

                    setTimeout(() => {
                        this.progress = 100;
                        this.scanMessage = 'ACCESS GRANTED.';
                        
                        // Stop camera stream
                        if (video.srcObject) {
                            video.srcObject.getTracks().forEach(track => track.stop());
                        }

                        // Play AI Voice
                        if ('speechSynthesis' in window) {
                            const msg = new SpeechSynthesisUtterance();
                            msg.text = "Identity verified. System operational.";
                            msg.volume = 1;
                            msg.rate = 1.2;
                            msg.pitch = 0.8;
                            window.speechSynthesis.speak(msg);
                        }

                        // Actually submit the form
                        setTimeout(() => {
                            document.getElementById('cyberLoginForm').submit();
                        }, 1000);
                        
                    }, 4000);
                }
            }));
        });
    </script>
</x-guest-layout>
